version: "3.9"
services:
  mongo:
    image: mongo:6
    container_name: mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build:
      context: ./backend
    container_name: fastapi_backend
    restart: unless-stopped
    depends_on:
      - mongo
    ports:
      - "8000:8000"
    environment:
      # inside compose use the mongo service hostname "mongo"
      - MONGO_URI=mongodb://mongo:27017/portfolioDB

  frontend:
    build:
      context: ./frontend
      args:
        - REACT_APP_API_URL=http://backend:8000
    container_name: react_frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "3000:80"

volumes:
  mongo_data:
